### PR TITLE
Patch update 2.1.7

### PR DESCRIPTION
**Pull request by roderickhsiao**
would be good to release the dep change 

https://github.com/jonschlinkert/micromatch/commit/d89a12526ce3987f3d6170cb499d8cf2585a7ddb
https://github.com/jonschlinkert/micromatch/commit/770053e5b2b4ebaf9e23633391654e52b223e6b4

Thanks!

### CODE REVIEW

**Comment by jonschlinkert** [comment]
@es128 want to release or do a beta with the changes? fwiw I've been working on the refactor, so I'm feeling pretty conservative right now.

**Comment by roderickhsiao** [comment]
for us the main purpose is to upgrade `object.omit` as we are having two versions download with the same dependency tree (we are using `babel`), but fine if you guys feel want to release laster.

Thanks!

**Comment by jonschlinkert** [comment]
ok, good to know. thanks for the feedback

**Comment by es128** [comment]
How can we assess whether this is safe as a patch release? I suspect it isn't.

I think the better approach here is renewed attention to #27, which may just translate into waiting for the refactor and tolerating the present circumstances.

@roderickhsiao why are the two versions of isobject a concern for you? This is how npm is intended to work.

**Comment by roderickhsiao** [comment]
@es128 

For server side, two versions increase the disk usage of our server, and with high traffic, the CPU spikes and potentially bring down the server if the disk usage is too high

For client side, (probably not in this case as we dont use babel in client side) if we are using webpack/browserfiy, two different version cannot be dedup, which means that it increase greatly the javascript size and potentially harm the performance.

**Comment by es128** [comment]
> increase the disk usage of our server

*very* minuscule impact in this case (as with most cases in npm packages, hence the design of its dep trees)

And as you said, no client-side impact in this circumstance.

You've described two philosophical issues with multiple versions of a dep. Doesn't sound like this is actually impacting you negatively. Doubt it's causing problems for anyone else either.

So I think we're safe to wait for the next proper iteration of micromatch.

**Comment by roderickhsiao** [comment]
correct, this one is actually not really changes anything (usually we saw greatly changes like `lodash`, `async` stuff, we do decrease quite a lot by aligning the version, its quite painful actually) 

I am fine with the next iteration :)

**Pull request closed without merging**
