### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by MartinKolarik**
Starting with [should v7](https://github.com/shouldjs/should.js/wiki/Breaking-changes), using the functions as getters is not supported. Without actually invoking the functions, nothing is being tested. 

In addition to fixing this, the PR also adds specific major version of mocha and should to package.json, to prevent other breaking changes affecting the tests in the future.

### CODE REVIEW

**Comment by MartinKolarik** [comment]
Just a note that this doesn't modify anything else - those failing tests on Travis were failing before as well.

**Comment by jonschlinkert** [comment]
> those failing tests on Travis were failing before as well.

hmm, are you sure? it looks like the tests are all passing on master. I'll have more time to look tomorrow, but it looks like the only tests failing in the pr are `.any` tests, I'm not sure why yet. 

thanks! I'll review more tomorrow and get this merged!

**Comment by MartinKolarik** [comment]
Yes, if you look at the diff, you'll see I only added the invocation parentheses. Unless I'm missing something, they were "passing" before because the assertions were not actually executed.

**Comment by jonschlinkert** [comment]
> I only added the invocation parentheses.

you're right, I see what you mean. Given the consistency of where they are failing it will probably (hopefully) be an easy fix. 

I didn't forget, just finishing up something first!

**Comment by MartinKolarik** [comment]
I took a look at what's actually failing and the good news is there's most likely no bug in micromatch. The tests for `.any()` exactly match the tests for `.contains()` - the only difference is the name of the method, so it looks you might have copied them and forgot to change the expected return values.

**Comment by jonschlinkert** [comment]
> t looks you might have copied them and forgot to change the expected return values.

great! copying tests to save time sounds like something I'd do, and I'm known to be a little absent minded now and then, lol. Good catch, and thank you for taking the time to review.

**Comment by MartinKolarik** [comment]
I updated the expected values and the `.any()` tests now pass, so this can be merged. However, the latest update of expand-brackets is causing one of other tests to fail, because of [this new check](https://github.com/jonschlinkert/expand-brackets/blob/master/index.js#L39-L41).

**Comment by jonschlinkert** [comment]
thanks again! I'm fighting off a bad cold, might take me a couple of days to catch up.

**Comment by MartinKolarik** [comment]
no problem, hope you get better soon :smile:

**Comment by MartinKolarik** [comment]
any update on this and #58/#61?

**Comment by jonschlinkert** [comment]
really sorry, this is taking a longer than usual for me to review. I won't be able to look until Tues

**Comment by jonschlinkert** [comment]
published and released as 2.3.8. thanks again and sorry for the delay (fwiw it's been a rough couple of weeks.. I had a funeral this week)

**Comment by MartinKolarik** [comment]
>(fwiw it's been a rough couple of weeks.. I had a funeral this week)

really sorry to hear that

**Comment by jonschlinkert** [comment]
thank you, I appreciate it

**Pull request merged**
