### PR TITLE
Globstar adjustments

### LINKED ISSUE #15: Bug with partial wildcards
```
> mm.isMatch('../test-fixtures/add.txt', '../test-fixtures/**/a*.txt')
true
> mm.isMatch('../test-fixtures/add.txt', '../test-*/**/a*.txt')
false
> mm.isMatch('../test-fixtures/subdir/subsub/a.txt', '../test-*/**/a*.txt')
false
> mm.isMatch('../test-fixtures/subdir/subsub/ab.txt', '../test-*/**/a*.txt')
true
```

Realized this is the cause of a few newly failing tests in chokidar

### PR DESCRIPTION
**Pull request by es128**
Not yet a complete fix.

Resolves #15
(when complete)

### CODE REVIEW

**Comment by jonschlinkert** [comment]
thanks!

**Comment by tunnckoCore** [comment]
this was very very bad change!

**Comment by es128** [comment]
Can you explain what problem you're having as a result of this?

What do you think the behavior should be for patterns like https://github.com/jonschlinkert/micromatch/pull/16/files#diff-0695d9db3c89e5879a8ab1497522e46eR92 ?

**Comment by tunnckoCore** [comment]
everything but not true :)

**Comment by jonschlinkert** [comment]
> it was great you follow the spec

I think it still does. It will always be a bigger challenge figuring out the parts the spec isn't clear on. 

> this was very very bad change!

well, let's just take a step back and discuss the changes, and if something is broken, we will focus on fixing it. I think a good start would be to show actual breaking code (e.g. not contrived code that wouldn't actually be used in a project)

**Comment by tunnckoCore** [comment]
> I think a good start would be to show actual breaking code

actually I dont have, cuz Im not using micromatch yet, but just looks logicless for me.

**Comment by es128** [comment]
@tunnckoCore I am interested in your perspective, but you're really not explaining what your objections are. So far your comments come across like a bunch of panicky flailing.

These changes were done in pursuit of solving actual problems and aligning behavior with what we (and users afaict) expect.

**Pull request merged**
