### PR TITLE
Fix #19 (partial wildcard matching)

### LINKED ISSUE #19: Partial wildcard bug (without globstar)
Uncovered by @tunnckoCore in #15 (thank you). Opening a new issue to track resolution.

```js
console.log(micromatch.isMatch('a/z.js', 'a/z*.js'));
//=> should be true
console.log(micromatch(paths, '*/z*.js'));
//=> should be [ 'a/z.js' ]
```

```js
// multimatch

console.log(multimatch(paths, '*/z*.js'));
//=> [ 'a/z.js' ]
```

### PR DESCRIPTION
**Pull request by es128**
Just getting a PR started with failing tests.

Do not intend for this to be merged until commits that fix the issue have also been added.

### CODE REVIEW

**Comment by jonschlinkert** [comment]
thanks for creating this!

**Comment by es128** [comment]
Ok I figured out the issue. When a `*` is by itself, it must match *something*, but if it's preceded by other non-separator characters, it doesn't have to. The `nodot` additions to the regex create the interference preventing `a/z.js` from matching on `a/z*.js` because `.` ends up being the next character.

The issue does not occur without a directory in front because of the special `expandFilename` handling.

**Comment by es128** [comment]
Fixed the narrow case I was focusing on with ce96bec, but I'm not sure whether there is any better way that doesn't require creating this special case.

@jonschlinkert look forward to your feedback. From my perspective it's ready to merge if you think this solution is ok.

**Comment by jonschlinkert** [comment]
looks good. feel free to merge, I'll be working on micromatch after lunch so I can do it then if you don't get a chance. thanks!

**Pull request merged**
