### PR TITLE
update related section

### PR DESCRIPTION
**Pull request by tunnckoCore**
- sorted, truncated related section
- add [gulp-micromatch](http://j.mp/1aeoVZF) to it
- plus fix `npm run benchmark` to `node benchmark`

### CODE REVIEW

**Comment by es128** [comment]
This repo uses [verb](https://github.com/assemble/verb) to generate its readme. You won't be able to do the truncation thing, but you can apply your other changes to [.verb.md](https://github.com/jonschlinkert/micromatch/blob/master/.verb.md) in a new PR

**Comment by jonschlinkert** [comment]
yeah, thanks for the fix on `npm run benchmark`, forgot that was removed from `package.json` scripts.

> You won't be able to do the truncation thing

Do you mean the `[more]` links? Those are auto-generated in the latest `helper-related`, which is what verb uses to generate the list.

@tunnckoCore it looks like you used verb to generate the readme, but you didn't change the `.verb.md`, did you do it manually?

**Comment by tunnckoCore** [comment]
haha, yea I forgot about verb and `.verb.md`. 

>  it looks like you used verb to generate the readme, but you didn't change the .verb.md, did you do it manually?

like a magic? lol :laughing: 
Yea, I use [npm-related cli](https://github.com/tunnckoCore/npm-related)

**Comment by tunnckoCore** [comment]
doh.. I mean, verb.md

**Comment by tunnckoCore** [comment]
@jonschlinkert hmmm, okey what should I use finally? verb-cli globally + verb locally or? damn lol

**Comment by tunnckoCore** [comment]
oo okey, verb-cli, cool.

**Comment by jonschlinkert** [comment]
yep, you got it. `verb-cli`

**Comment by tunnckoCore** [comment]
new PR sent

**Pull request closed without merging**
